version: "3.9"
services:
  es:
    image: elasticsearch:7.17.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      TZ: Asia/Seoul
      discovery.type: single-node
    networks:
      - fream-default

  kibana:
    image: kibana:7.17.0
    ports:
      - "5601:5601"
    depends_on:
      - es
    links:
      - es:es
    environment:
      TZ: Asia/Seoul
      ELASTICSEARCH_HOSTS: '["http://es:9200"]'
    networks:
      - fream-default

  fluentd:
    build: fluentd
    image: fream-fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - es:es
    depends_on:
      - es
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - fream-default

  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - "9411:9411"
    environment:
      TZ: Asia/Seoul
    networks:
      - fream-default

  product-service:
    build: product-service
    image: fream-product-service
    ports:
      - "8180:8080"
    depends_on:
      - zipkin
      - product-service-db
    links:
      - zipkin:zipkin
      - product-service-db:fream-product-service-db
      - fluentd:fluentd
    environment:
      SPRING_PROFILES_ACTIVE: local
      TZ: Asia/Seoul
      FREAM_DB_URL: fream-product-service-db
      FREAM_DB_USERNAME: test
      FREAM_DB_PASSWORD: test
    restart: always
    networks:
      - fream-default
      - product-service
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: product-service

  product-service-db:
    image: mysql:8
    platform: linux/amd64
    ports:
      - "33310:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: fream-product
    command: mysqld --default-authentication-plugin=mysql_native_password --ngram-token-size=2
    networks:
      - product-service

networks:
  fream-default:
    name: fream
  product-service:
    name: fream-product-service