#!/bin/sh

cd $(dirname ${BASH_SOURCE[0]}) && cd ../..
SCRIPT_DIR=$(pwd)

./gradlew clean build -x test
if [ $? -eq 0 ]; then
  echo "Checking the project integrity has been completed."
else
  echo "Fail to check the project integrity."
  exit 1
fi
