spring:
  flyway:
    schemas: fream
    locations:
      - classpath:db/migration
      - classpath:db/migration-prod-seed
  lifecycle:
    timeout-per-shutdown-phase: 1m
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
server:
  shutdown: graceful
