spring:
  flyway:
    schemas: fream
    locations:
      - classpath:db/migration
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
