spring:
  flyway:
    schemas: fream
    locations:
      - classpath:db/migration
      - classpath:db/migration-seed
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
