spring:
  flyway:
    schemas: fream
    locations:
      - classpath:db/migration
      - classpath:db/migration-seed
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
  datasource:
    url: jdbc:mysql://localhost:3306/fream?useSSL=false&allowPublicKeyRetrieval=true
    username: test
    password: test
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
logging:
  level:
    root: DEBUG
