spring:
  flyway:
    schemas: fream
    locations:
      - classpath:db/migration
      - classpath:db/migration-seed
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
logging:
  level:
    root: debug
