spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: jdbc:mysql://${FREAM_DB_URL:localhost}:${FREAM_DB_PORT:3306}/${FREAM_DB_SCHEME:fream-product}?useSSL=false
    username: ${FREAM_DB_USERNAME}
    password: ${FREAM_DB_PASSWORD}
server:
  port: ${SERVER_PORT:8080}